/**
 * ScriptRunner Exporter: generates SMS (ScriptRunner Migration Suite) scaffold.
 *
 * Creates an extensions.yaml and Groovy stub files compatible with Adaptavist's
 * ScriptRunner Dev and Deployment Tool:
 *   https://bitbucket.org/adaptavistlabs/migration-example-project
 *   https://docs.adaptavist.com/sms/latest/scriptrunner-dev-and-deployment-tool
 *
 * Since ScriptRunner script content is NOT available via Jira's workflow API
 * (only the Connect rule reference is stored), this generates a scaffold
 * that the user completes manually by pasting their Groovy code.
 */

const fs = require("fs");
const path = require("path");
const { detectScriptRunnerRules } = require("./workflowTransformer");

class ScriptRunnerExporter {
  constructor(collectDir, log) {
    this.collectDir = collectDir;
    this.log = log || console.log;
    this.scaffoldDir = path.join(collectDir, "scriptrunner-scaffold");
  }

  /**
   * Generate the SMS scaffold from collected workflow data.
   *
   * @param {Array} collectedWorkflows - [{name, file}, ...] from metadata.json
   */
  async generate(collectedWorkflows) {
    fs.mkdirSync(this.scaffoldDir, { recursive: true });
    const groovyDir = path.join(this.scaffoldDir, "groovy");
    fs.mkdirSync(groovyDir, { recursive: true });

    const allRules = [];

    // Detect ScriptRunner rules in each workflow
    for (const wfEntry of collectedWorkflows) {
      const wfPath = path.join(this.collectDir, wfEntry.file);
      if (!fs.existsSync(wfPath)) continue;

      const workflow = JSON.parse(fs.readFileSync(wfPath, "utf8"));
      const rules = detectScriptRunnerRules(workflow);
      allRules.push(...rules);
    }

    if (allRules.length === 0) {
      this.log("  No ScriptRunner rules found in collected workflows");
      return;
    }

    this.log(`  Found ${allRules.length} ScriptRunner rule(s) across workflows`);

    // Group rules by workflow -> transition
    const grouped = this.groupRules(allRules);

    // Generate extensions.yaml
    this.generateExtensionsYaml(grouped, groovyDir);

    // Generate Groovy stubs
    this.generateGroovyStubs(allRules, groovyDir);

    // Generate README
    this.generateReadme(allRules.length);

    this.log(`  Scaffold generated at: ${this.scaffoldDir}`);
    this.log(`    extensions.yaml - SMS workflow config`);
    this.log(`    groovy/ - Groovy stub files (${allRules.length} files)`);
    this.log(`    README.md - Setup instructions`);
  }

  groupRules(rules) {
    const grouped = new Map();
    for (const rule of rules) {
      if (!grouped.has(rule.workflowName)) {
        grouped.set(rule.workflowName, new Map());
      }
      const transitions = grouped.get(rule.workflowName);
      if (!transitions.has(rule.transitionName)) {
        transitions.set(rule.transitionName, []);
      }
      transitions.get(rule.transitionName).push(rule);
    }
    return grouped;
  }

  generateExtensionsYaml(grouped, groovyDir) {
    const lines = [];
    lines.push("# ScriptRunner SMS extensions.yaml");
    lines.push("# Generated by clone_workflow_rules --export-scriptrunner-scaffold");
    lines.push(`# Date: ${new Date().toISOString()}`);
    lines.push("#");
    lines.push("# Instructions:");
    lines.push("#   1. Copy this file to cloud/src/main/resources/extensions.yaml in your SMS project");
    lines.push("#   2. Copy groovy/ stubs to cloud/src/main/groovy/");
    lines.push("#   3. Fill in actual Groovy script content in each stub");
    lines.push("#   4. Run: ./gradlew cloud:deploy-workflow-all");
    lines.push("");
    lines.push("workflows:");

    for (const [workflowName, transitions] of grouped) {
      lines.push(`  - workflowName: "${workflowName}"`);
      lines.push(`    transitions:`);

      for (const [transitionName, rules] of transitions) {
        lines.push(`      - transitionName: "${transitionName}"`);

        const postFunctions = rules.filter((r) => r.ruleType === "postFunction");
        const conditions = rules.filter((r) => r.ruleType === "condition");
        const validators = rules.filter((r) => r.ruleType === "validator");

        if (postFunctions.length > 0) {
          lines.push(`        postFunctions:`);
          for (let i = 0; i < postFunctions.length; i++) {
            const scriptFile = this.getGroovyPath(workflowName, transitionName, "postfunction", i);
            lines.push(`          - description: "Post-function ${i + 1} from migration"`);
            lines.push(`            scriptFile: "${scriptFile}"`);
            // Add config as YAML comment for identification
            if (postFunctions[i].configuration) {
              lines.push(`            # Original config: ${this.truncateConfig(postFunctions[i].configuration)}`);
            }
          }
        }

        if (conditions.length > 0) {
          lines.push(`        conditions:`);
          for (let i = 0; i < conditions.length; i++) {
            const scriptFile = this.getGroovyPath(workflowName, transitionName, "condition", i);
            lines.push(`          - description: "Condition ${i + 1} from migration"`);
            lines.push(`            scriptFile: "${scriptFile}"`);
            if (conditions[i].configuration) {
              lines.push(`            # Original config: ${this.truncateConfig(conditions[i].configuration)}`);
            }
          }
        }

        if (validators.length > 0) {
          lines.push(`        validators:`);
          for (let i = 0; i < validators.length; i++) {
            const scriptFile = this.getGroovyPath(workflowName, transitionName, "validator", i);
            lines.push(`          - description: "Validator ${i + 1} from migration"`);
            lines.push(`            scriptFile: "${scriptFile}"`);
            if (validators[i].configuration) {
              lines.push(`            # Original config: ${this.truncateConfig(validators[i].configuration)}`);
            }
          }
        }
      }
    }

    const yamlPath = path.join(this.scaffoldDir, "extensions.yaml");
    fs.writeFileSync(yamlPath, lines.join("\n") + "\n");
  }

  generateGroovyStubs(rules, groovyDir) {
    for (let i = 0; i < rules.length; i++) {
      const rule = rules[i];
      const relativePath = this.getGroovyPath(
        rule.workflowName,
        rule.transitionName,
        rule.ruleType === "postFunction" ? "postfunction" : rule.ruleType,
        this.getIndexForRule(rules, rule, i),
      );
      const fullPath = path.join(groovyDir, relativePath);

      // Ensure directory exists
      fs.mkdirSync(path.dirname(fullPath), { recursive: true });

      const configStr = rule.configuration
        ? JSON.stringify(rule.configuration, null, 2)
        : "N/A";

      const content = [
        "/**",
        ` * Workflow: ${rule.workflowName}`,
        ` * Transition: ${rule.transitionName}`,
        ` * Type: ${rule.ruleType}`,
        ` * Original rule type: ${rule.type}`,
        " *",
        " * Original configuration from source instance:",
        ...configStr.split("\n").map((line) => ` * ${line}`),
        " *",
        " * TODO: Paste your Groovy script content below.",
        " * Export from: ScriptRunner > Script Manager on the source instance,",
        " * or rewrite from the DC version if migrating from Data Center.",
        " */",
        "",
        "// TODO: paste your Groovy script content here",
        "",
      ].join("\n");

      fs.writeFileSync(fullPath, content);
    }
  }

  generateReadme(ruleCount) {
    const content = `# ScriptRunner SMS Scaffold

Generated by \`clone_workflow_rules --export-scriptrunner-scaffold\`

## Overview

This scaffold contains ${ruleCount} ScriptRunner workflow rule(s) detected in the collected workflows.
ScriptRunner script content is NOT available via Jira's workflow API, so stub files have been
generated that you need to fill in manually.

## Setup Instructions

### 1. Clone the SMS deployment project

\`\`\`bash
git clone https://bitbucket.org/adaptavistlabs/migration-example-project.git sms-deploy
cd sms-deploy
\`\`\`

### 2. Configure credentials

Edit \`gradle.properties\`:
\`\`\`properties
jiraBaseUrl=https://your-target-instance.atlassian.net
\`\`\`

Edit \`~/.gradle/gradle.properties\`:
\`\`\`properties
jiraUserEmail=your-email@example.com
jiraApiToken=your-api-token
\`\`\`

### 3. Copy scaffold files

\`\`\`bash
cp extensions.yaml <sms-deploy>/cloud/src/main/resources/extensions.yaml
cp -r groovy/* <sms-deploy>/cloud/src/main/groovy/
\`\`\`

### 4. Fill in Groovy script content

Each \`.groovy\` stub file contains a TODO marker and the original configuration
from the source instance to help you identify which script goes where.

Export scripts from: **ScriptRunner > Script Manager** on the source instance.

### 5. Deploy

\`\`\`bash
cd <sms-deploy>
./gradlew cloud:deploy-workflow-all
\`\`\`

Or deploy individual rules:
\`\`\`bash
./gradlew "deploy-workflow-Post-function 1 from migration"
\`\`\`

## Requirements

- Java 17+ (recommend SDKMAN for management)
- Gradle (bundled via wrapper in the SMS project)
- ScriptRunner for Jira Cloud installed on the target instance

## References

- [SMS Documentation](https://docs.adaptavist.com/sms/latest/scriptrunner-dev-and-deployment-tool)
- [Supported Features](https://docs.adaptavist.com/sms/latest/scriptrunner-dev-and-deployment-tool/supported-features-and-limitations)
- [SMS Example Project](https://bitbucket.org/adaptavistlabs/migration-example-project)
`;

    const readmePath = path.join(this.scaffoldDir, "README.md");
    fs.writeFileSync(readmePath, content);
  }

  getGroovyPath(workflowName, transitionName, ruleType, index) {
    const safeWf = workflowName.replace(/[^a-zA-Z0-9_-]/g, "_");
    const safeTr = transitionName.replace(/[^a-zA-Z0-9_-]/g, "_");
    return `${safeWf}/${safeTr}_${ruleType}_${index}.groovy`;
  }

  getIndexForRule(allRules, rule, globalIndex) {
    // Count how many rules of the same type/workflow/transition come before this one
    let count = 0;
    for (let i = 0; i < globalIndex; i++) {
      const r = allRules[i];
      if (
        r.workflowName === rule.workflowName &&
        r.transitionName === rule.transitionName &&
        r.ruleType === rule.ruleType
      ) {
        count++;
      }
    }
    return count;
  }

  truncateConfig(config) {
    const str = JSON.stringify(config);
    return str.length > 120 ? str.substring(0, 120) + "..." : str;
  }
}

module.exports = ScriptRunnerExporter;
